 CLASS ztcl_i_purchasedocument_u  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS ztcl_i_purchasedocument_u  IMPLEMENTATION.
 ENDCLASS.
